Attribute VB_Name = "Transfert_Liste_à_Comptabilité"


Sub Transfert_Liste_à_Comptabilité_D()


Workbooks("Comptes").Worksheets("Liste").Range("T12").Copy Workbooks("Comptabilité").Worksheets("D").Range("B7")
Workbooks("Comptes").Worksheets("Liste").Range("T13").Copy Workbooks("Comptabilité").Worksheets("D").Range("B75")
Workbooks("Comptes").Worksheets("Liste").Range("T14").Copy Workbooks("Comptabilité").Worksheets("D").Range("B143")
Workbooks("Comptes").Worksheets("Liste").Range("T15").Copy Workbooks("Comptabilité").Worksheets("D").Range("B211")
Workbooks("Comptes").Worksheets("Liste").Range("T16").Copy Workbooks("Comptabilité").Worksheets("D").Range("B279")
Workbooks("Comptes").Worksheets("Liste").Range("T17").Copy Workbooks("Comptabilité").Worksheets("D").Range("B347")
Workbooks("Comptes").Worksheets("Liste").Range("T18").Copy Workbooks("Comptabilité").Worksheets("D").Range("B415")
Workbooks("Comptes").Worksheets("Liste").Range("T19").Copy Workbooks("Comptabilité").Worksheets("D").Range("B483")
Workbooks("Comptes").Worksheets("Liste").Range("T20").Copy Workbooks("Comptabilité").Worksheets("D").Range("B551")
Workbooks("Comptes").Worksheets("Liste").Range("T21").Copy Workbooks("Comptabilité").Worksheets("D").Range("B619")
Workbooks("Comptes").Worksheets("Liste").Range("T22").Copy Workbooks("Comptabilité").Worksheets("D").Range("B687")
Workbooks("Comptes").Worksheets("Liste").Range("T23").Copy Workbooks("Comptabilité").Worksheets("D").Range("B755")
Workbooks("Comptes").Worksheets("Liste").Range("T24").Copy Workbooks("Comptabilité").Worksheets("D").Range("B823")
Workbooks("Comptes").Worksheets("Liste").Range("T25").Copy Workbooks("Comptabilité").Worksheets("D").Range("B891")
Workbooks("Comptes").Worksheets("Liste").Range("T26").Copy Workbooks("Comptabilité").Worksheets("D").Range("B959")
Workbooks("Comptes").Worksheets("Liste").Range("T27").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1027")
Workbooks("Comptes").Worksheets("Liste").Range("T28").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1095")
Workbooks("Comptes").Worksheets("Liste").Range("T29").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1163")
Workbooks("Comptes").Worksheets("Liste").Range("T30").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1231")
Workbooks("Comptes").Worksheets("Liste").Range("T31").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1299")
Workbooks("Comptes").Worksheets("Liste").Range("T32").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1367")
Workbooks("Comptes").Worksheets("Liste").Range("T33").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1435")
Workbooks("Comptes").Worksheets("Liste").Range("T34").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1503")
Workbooks("Comptes").Worksheets("Liste").Range("T35").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1571")
Workbooks("Comptes").Worksheets("Liste").Range("T36").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1639")
Workbooks("Comptes").Worksheets("Liste").Range("T37").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1707")
Workbooks("Comptes").Worksheets("Liste").Range("T38").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1775")
Workbooks("Comptes").Worksheets("Liste").Range("T39").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1843")
Workbooks("Comptes").Worksheets("Liste").Range("T40").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1911")
Workbooks("Comptes").Worksheets("Liste").Range("T41").Copy Workbooks("Comptabilité").Worksheets("D").Range("B1979")
Workbooks("Comptes").Worksheets("Liste").Range("T42").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2047")
Workbooks("Comptes").Worksheets("Liste").Range("T43").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2115")
Workbooks("Comptes").Worksheets("Liste").Range("T44").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2183")
Workbooks("Comptes").Worksheets("Liste").Range("T45").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2251")
Workbooks("Comptes").Worksheets("Liste").Range("T46").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2319")
Workbooks("Comptes").Worksheets("Liste").Range("T47").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2387")
Workbooks("Comptes").Worksheets("Liste").Range("T48").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2455")
Workbooks("Comptes").Worksheets("Liste").Range("T49").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2523")
Workbooks("Comptes").Worksheets("Liste").Range("T50").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2591")
Workbooks("Comptes").Worksheets("Liste").Range("T51").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2659")
Workbooks("Comptes").Worksheets("Liste").Range("T52").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2727")
Workbooks("Comptes").Worksheets("Liste").Range("T53").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2795")
Workbooks("Comptes").Worksheets("Liste").Range("T54").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2863")
Workbooks("Comptes").Worksheets("Liste").Range("T55").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2931")
Workbooks("Comptes").Worksheets("Liste").Range("T56").Copy Workbooks("Comptabilité").Worksheets("D").Range("B2999")
Workbooks("Comptes").Worksheets("Liste").Range("T57").Copy Workbooks("Comptabilité").Worksheets("D").Range("B3067")


End Sub


Sub Transfert_Liste_à_Comptabilité_C()


Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C12").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C7")

Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C14").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C143")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C15").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C211")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C16").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C279")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C17").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C347")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C18").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C415")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C19").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C483")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C20").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C551")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C21").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C619")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C22").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C687")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C23").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C755")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C24").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C823")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C25").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C891")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C26").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C959")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C27").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1027")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C28").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1095")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C29").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1163")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C30").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1231")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C31").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1299")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C32").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1367")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C33").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1435")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C34").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1503")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C35").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1571")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C36").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1639")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C37").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1707")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C38").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1775")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C39").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1843")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C40").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1911")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C41").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C1979")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C42").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2047")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C43").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2115")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C44").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2183")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C45").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2251")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C46").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2319")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C47").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2387")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C48").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2455")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C49").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2523")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C50").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2591")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C51").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2659")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C52").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2727")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C53").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2795")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C54").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2863")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C55").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2931")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C56").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C2999")
Workbooks("Comptes.xlsx").Worksheets("Liste").Range("C57").Copy Workbooks("Comptabilité.xlsx").Worksheets("C").Range("C3067")

End Sub

Sub Transfert_Liste_à_Comptabilité_F()


Workbooks("Comptes").Worksheets("Liste").Range("AK12").Copy Workbooks("Comptabilité").Worksheets("F").Range("B7")
Workbooks("Comptes").Worksheets("Liste").Range("AK13").Copy Workbooks("Comptabilité").Worksheets("F").Range("B75")
Workbooks("Comptes").Worksheets("Liste").Range("AK14").Copy Workbooks("Comptabilité").Worksheets("F").Range("B143")
Workbooks("Comptes").Worksheets("Liste").Range("AK15").Copy Workbooks("Comptabilité").Worksheets("F").Range("B211")
Workbooks("Comptes").Worksheets("Liste").Range("AK16").Copy Workbooks("Comptabilité").Worksheets("F").Range("B279")
Workbooks("Comptes").Worksheets("Liste").Range("AK17").Copy Workbooks("Comptabilité").Worksheets("F").Range("B347")
Workbooks("Comptes").Worksheets("Liste").Range("AK18").Copy Workbooks("Comptabilité").Worksheets("F").Range("B415")
Workbooks("Comptes").Worksheets("Liste").Range("AK19").Copy Workbooks("Comptabilité").Worksheets("F").Range("B483")
Workbooks("Comptes").Worksheets("Liste").Range("AK20").Copy Workbooks("Comptabilité").Worksheets("F").Range("B551")
Workbooks("Comptes").Worksheets("Liste").Range("AK21").Copy Workbooks("Comptabilité").Worksheets("F").Range("B619")
Workbooks("Comptes").Worksheets("Liste").Range("AK22").Copy Workbooks("Comptabilité").Worksheets("F").Range("B687")
Workbooks("Comptes").Worksheets("Liste").Range("AK23").Copy Workbooks("Comptabilité").Worksheets("F").Range("B755")
Workbooks("Comptes").Worksheets("Liste").Range("AK24").Copy Workbooks("Comptabilité").Worksheets("F").Range("B823")
Workbooks("Comptes").Worksheets("Liste").Range("AK25").Copy Workbooks("Comptabilité").Worksheets("F").Range("B891")
Workbooks("Comptes").Worksheets("Liste").Range("AK26").Copy Workbooks("Comptabilité").Worksheets("F").Range("B959")
Workbooks("Comptes").Worksheets("Liste").Range("AK27").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1027")
Workbooks("Comptes").Worksheets("Liste").Range("AK28").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1095")
Workbooks("Comptes").Worksheets("Liste").Range("AK29").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1163")
Workbooks("Comptes").Worksheets("Liste").Range("AK30").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1231")
Workbooks("Comptes").Worksheets("Liste").Range("AK31").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1299")
Workbooks("Comptes").Worksheets("Liste").Range("AK32").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1367")
Workbooks("Comptes").Worksheets("Liste").Range("AK33").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1435")
Workbooks("Comptes").Worksheets("Liste").Range("AK34").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1503")
Workbooks("Comptes").Worksheets("Liste").Range("AK35").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1571")
Workbooks("Comptes").Worksheets("Liste").Range("AK36").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1639")
Workbooks("Comptes").Worksheets("Liste").Range("AK37").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1707")
Workbooks("Comptes").Worksheets("Liste").Range("AK38").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1775")
Workbooks("Comptes").Worksheets("Liste").Range("AK39").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1843")
Workbooks("Comptes").Worksheets("Liste").Range("AK40").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1911")
Workbooks("Comptes").Worksheets("Liste").Range("AK41").Copy Workbooks("Comptabilité").Worksheets("F").Range("B1979")
Workbooks("Comptes").Worksheets("Liste").Range("AK42").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2047")
Workbooks("Comptes").Worksheets("Liste").Range("AK43").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2115")
Workbooks("Comptes").Worksheets("Liste").Range("AK44").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2183")
Workbooks("Comptes").Worksheets("Liste").Range("AK45").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2251")
Workbooks("Comptes").Worksheets("Liste").Range("AK46").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2319")
Workbooks("Comptes").Worksheets("Liste").Range("AK47").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2387")
Workbooks("Comptes").Worksheets("Liste").Range("AK48").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2455")
Workbooks("Comptes").Worksheets("Liste").Range("AK49").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2523")
Workbooks("Comptes").Worksheets("Liste").Range("AK50").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2591")
Workbooks("Comptes").Worksheets("Liste").Range("AK51").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2659")
Workbooks("Comptes").Worksheets("Liste").Range("AK52").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2727")
Workbooks("Comptes").Worksheets("Liste").Range("AK53").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2795")
Workbooks("Comptes").Worksheets("Liste").Range("AK54").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2863")
Workbooks("Comptes").Worksheets("Liste").Range("AK55").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2931")
Workbooks("Comptes").Worksheets("Liste").Range("AK56").Copy Workbooks("Comptabilité").Worksheets("F").Range("B2999")
Workbooks("Comptes").Worksheets("Liste").Range("AK57").Copy Workbooks("Comptabilité").Worksheets("F").Range("B3067")


End Sub
